export { Card } from './ui/Card'
export { MobileCard } from './ui/MobileCard'
export { Poster } from './ui/Poster'
export type { Movie, MovieDetail, MovieType } from './model/types'
export { CATALOG, ALL_GENRES, MOCK_DETAIL } from './model/catalog'
export { getMoviesPage } from './api/getMoviesPage'
export type { CatalogParams, CatalogPageResult } from './api/getMoviesPage'
export * from './hooks'